### ISSUE TITLE
Invalid background size error: (-215) size() == mask.size() in function copyTo

### ISSUE THREAD

**Issue by mehdilauters** [floe/deepbacksub#1]
Thank you for this fun project!

I ran into the background issue at runtime.
Just adding ````cv::resize(bg,bg,cv::Size(width,height))```` after loading the background did the trick: https://github.com/floe/deepbacksub/blob/master/deepseg.cc#L94

Maybe just changing ````background.png```` to ````background_retro.png```` in the sample will avoid the ugly opencv exception only meaning the file does not exist

Regards

**Comment by gravatite** [comment]
Adding that line fixed the problem I ran into.  Thanks!

**Comment by floe** [comment]
Done and done. Thanks for the suggestion! I'll leave this open for the moment because it looks like `cv::resize` is messing with the color ordering, though (BGR <-> RGB)...
