### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by kontextbewusst** [floe/deepbacksub#10]
Is there any chance to make this work on macOS? Would definitely fancy up our Slack calls!

**Comment by floe** [comment]
I think the recommended way to do this on Mac would be to use [CamTwist](http://camtwiststudio.com/) to capture the output of the debug window (set `debug = 1` in `deepseg.cc`) and forward that to Slack/Skype/whatever. See also https://github.com/alievk/avatarify for instructions.

**Comment by floe** [comment]
[Webcamoid](https://webcamoid.github.io/) might also work.

**Comment by floe** [comment]
BTW, did you manage to build it on Mac?

**Comment by kontextbewusst** [comment]
Thanks for the suggestions! No I haven't tried yet for lack of time, but I asked Hagen to give it a shot 😬

**Comment by jiangjianping** [comment]
@floe,
I want to combine this with WEBRTC, so that it can be used on multiple platform while the device performance is affordable. The target is at least 20fps with 360P-720P. Is it possible?

**Comment by floe** [comment]
@jiangjianping 360p @20FPS probably yes, try setting threads to 4 or 8 (if you have a sufficiently beefy CPU). For 720p, I think you would need some kind of HW acceleration like a GPU.

**Comment by jiangjianping** [comment]
@floe 

thanks, I will try. Do you use hw acceleration when you get the 10fps?

**Comment by floe** [comment]
No, that was with an old i5 CPU, 2 threads.

**Comment by jiangjianping** [comment]
@floe ,
Could you use body-pix like  https://github.com/allo-/virtual_webcam_background  do? I found It has better quality.

**Comment by floe** [comment]
I was planning to try that anyway; I'll have to look if body-pix can be converted to TFLite.

**Comment by jiangjianping** [comment]
Great! BTW, modprobe v4l2loopback devices=1 max_buffers=2 exclusive_caps=1 card_label="VirtualCam" , then chrome will not work.

**Comment by phlash** [comment]
Looking like an OBS Studio plugin might be a good route for non-Linux systems?

**Comment by BenBE** [comment]
> Looking like an OBS Studio plugin might be a good route for non-Linux systems?

Yes, but that'd be subject for a new issue. Closing here for now, as the original question has been answered.
