### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by ivanfet** [floe/deepbacksub#14]
Hi
Is it possible for someone who has this program working to list out the process to install everything and setup deepbacksub so it runs.  I have followed the list of requirements but I'm stuck on the error below. All the files are in the correct folders but something is not set up correct.

Error:
In file included from deepseg.cc:19:0:
tensorflow/lite/interpreter.h:26:10: fatal error: tensorflow/lite/allocation.h: No such file or directory
 #include "tensorflow/lite/allocation.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:39: recipe for target 'deepseg' failed
make: *** [deepseg] Error 1

Cheers Ivan

**Comment by floe** [comment]
So the compiler can't find your tensorflow installation. See https://github.com/floe/deepbacksub/blob/master/Makefile#L11-L13 for how to checkout tensorflow; the Makefile expects it in `../tensorflow.git/` relative to the project folder.

**Comment by bendavis78** [comment]
Might be better to add as a git submodule?

**Comment by floe** [comment]
@bendavis78 Good idea, actually. Will do that.
