### ISSUE TITLE
loopback error when launch deepseg

### ISSUE THREAD

**Issue by elpagano3** [floe/deepbacksub#17]
Hi,

I've successfully compiled deepsig, but when i execute deepseg shows me this error:

deepseg v0.1.0
(c) 2020 by floe@butterbrot.org
https://github.com/floe/deepseg
debug:  0
ccam:   /dev/video1
vcam:   /dev/video0
width:  640
height: 480
back:   background.png
threads:2
deepseg: loopback.cc:57: int loopback_init(const char*, int, int, int): Assertion `ret_code != -1' failed.
[1]    115948 abort (core dumped)  ./deepseg

Im working on Pop_OS 20.04, OpenCV 4.2 and tensorflow lite from repo.

**Comment by floe** [comment]
Is it possible that your devices are just swapped? I.e. try `./deepseg -c /dev/video0 -v /dev/video1`?

**Comment by elpagano3** [comment]
Yes, that works.  Thanks a lot!.
