### ISSUE TITLE
Test BodyPix network

### ISSUE THREAD

**Issue by floe** [floe/deepbacksub#19]
https://storage.googleapis.com/tfjs-models/demos/body-pix/index.html

**Comment by jiangjianping** [comment]
what's the progress of bodypix integration?

**Comment by floe** [comment]
I managed to convert body-pix to TFLite format: https://github.com/floe/deepbacksub/blob/master/body-pix.tflite
However, I haven't yet succeeded in getting it to run. PRs welcome :-)

**Comment by jiangjianping** [comment]
use TF like this? https://github.com/allo-/virtual_webcam_background

**Comment by jiangjianping** [comment]
Not really. I test it with no GPU.

**Comment by floe** [comment]
Hm, OK, I'll see if I can use regular TF instead (although after a quick test, it seems to be about ~ 30% slower).

**Comment by jiangjianping** [comment]
Quick test with python?  How about the C language?

**Comment by floe** [comment]
Managed to get the conversion working after all, closed via fb74c7a.
