### ISSUE TITLE
core dumped sometimes

### ISSUE THREAD

**Issue by jiangjianping** [floe/deepbacksub#20]
deepseg.cc

called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.10-dev) /home/zj/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

at the line 233: cv::Mat roi = raw(roidim);

**Comment by floe** [comment]
Hm 🤔 Can you print the dimensions of `raw` and `roidim` when that happens? The only reason I can think of is when the camera doesn't properly switch to the requested resolution...

**Comment by jiangjianping** [comment]
You are right. when the error happens, the rows and cols are zero. It is not the resolution issue, it means there is no captured data at that time. The thread is more quick than capture thread. I suggest we should add the if statement there.  

rows=360 cols=640 roi x=140 y=0 width=360 height=360
rows=0 cols=0 roi x=140 y=0 width=360 height=360
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.10-dev) /home/zj/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

**Comment by jiangjianping** [comment]
The following code worker for me.
     if (raw.rows == 0 || raw.cols == 0)
     {
                        usleep(100);
                        continue;
      }
     cv::Mat roi = raw(roidim);
