### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by tobi-weber** [floe/deepbacksub#22]
Hello,

I get the following compile error and cannot find the problem:

g++ deepseg.cc loopback.cc -Ofast -march=native -fno-trapping-math -fassociative-math -funsafe-math-optimizations -Wall -pthread -I ../tensorflow.git -I ../tensorflow.git/tensorflow/lite/tools/make//downloads/absl -I ../tensorflow.git/tensorflow/lite/tools/make//downloads/flatbuffers/include -I/usr/include/opencv4/opencv -I/usr/include/opencv4 -lrt -ldl  -L ../tensorflow.git/tensorflow/lite/tools/make//gen/linux_x86_64/lib/ -ltensorflow-lite -lopencv_stitching -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_highgui -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_quality -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core -o deepseg
/usr/bin/ld: ../tensorflow.git/tensorflow/lite/tools/make//gen/linux_x86_64/lib//libtensorflow-lite.a(interpreter_builder.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:27: deepseg] Fehler 1

Thank you

**Comment by floe** [comment]
Just a guess, but this might mean that your tensorflow-lite library binary was built with a different GLIBC version than the one you're currently on. Can you try rebuilding tflite?

**Comment by jiangjianping** [comment]
this  issue can be  solved: add -ldl to LDFLAGS, I encounter the same issue with v2.3 tensor lite.

**Comment by floe** [comment]
That's weird, because `-ldl` is already in the Makefile?

**Comment by jiangjianping** [comment]
-ldl is added by me to solve this issue.

**Comment by floe** [comment]
Yes, but in the commandline from @tobi-weber, `-ldl` is already included (3rd line)?

**Comment by tobi-weber** [comment]
"LDFLAGS = -lrt -ldl" is included in the Makefile. Maybe there is a problem with tensorflow-lite.
I installed tensorflow-lite as described in the description. My GLIBC-Version is 2.3.1. I am using Debian testing.

Thank you

**Comment by jiangjianping** [comment]
Sorry, -ldl should be added here
 **LDFLAGS += -L $(TFLITE)/gen/linux_x86_64/lib/ -ltensorflow-lite -ldl**
1. without -ldl there, I got the same problem as @tobi-weber 
root@zj-desktop:/home/zj/deepbacksub# make
g++ deepseg.cc loopback.cc -Ofast -march=native -fno-trapping-math -fassociative-math -funsafe-math-optimizations -Wall -pthread -g -I ../tensorflow.git -I ../tensorflow.git/tensorflow/lite/tools/make//downloads/absl -I ../tensorflow.git/tensorflow/lite/tools/make//downloads/flatbuffers/include -I/usr/include/opencv -lrt -ldl -L ../tensorflow.git/tensorflow/lite/tools/make//gen/linux_x86_64/lib/ -ltensorflow-lite  -lopencv_dnn -lopencv_highgui -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_videoio -lopencv_imgcodecs -lopencv_features2d -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core -o deepseg
/usr/bin/ld: ../tensorflow.git/tensorflow/lite/tools/make//gen/linux_x86_64/lib//libtensorflow-lite.a(interpreter_builder.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
2. after add -ldl here, problem is solved
g++ deepseg.cc loopback.cc -Ofast -march=native -fno-trapping-math -fassociative-math -funsafe-math-optimizations -Wall -pthread -g -I ../tensorflow.git -I ../tensorflow.git/tensorflow/lite/tools/make//downloads/absl -I ../tensorflow.git/tensorflow/lite/tools/make//downloads/flatbuffers/include -I/usr/include/opencv -lrt -ldl -L ../tensorflow.git/tensorflow/lite/tools/make//gen/linux_x86_64/lib/ -ltensorflow-lite -ldl -lopencv_dnn -lopencv_highgui -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_videoio -lopencv_imgcodecs -lopencv_features2d -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core -o deepseg
root@zj-desktop:/home/zj/deepbacksub#

**Comment by tobi-weber** [comment]
Thank you, this fixes the problem.
