### ISSUE TITLE
Possible Model Improvements

### ISSUE THREAD

**Issue by bobbens** [floe/deepbacksub#24]
While searching for background removal solutions, I found a [similar project](https://elder.dev/posts/open-source-virtual-background/) that doesn't have a proper repository. It apparently uses the [bodypix 2](https://blog.tensorflow.org/2019/11/updated-bodypix-2.html) model for segmentation which is specialized for humans. Seeing as they both are tensorflow with similar API, it might be worth adding this alternative model as an option for higher performance.

**Comment by floe** [comment]
NB, I already have a body-pix model here in the repo, you can test it if you run deepseg with parameter "-m body-pix(...).tflite". It's not optimized yet, however.

**Comment by wasmitnetzen** [comment]
There is a lot of information [in this repo](https://github.com/anilsathyan7/Portrait-Segmentation). I'm using one of their models ([deconv_bnoptimized_munet.h5](https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/models/transpose_seg/deconv_bnoptimized_munet.h5) in a similar project of mine, but the performance is not much better. But there might be another model there.

**Comment by floe** [comment]
Oho, interesting find, thanks!

**Comment by floe** [comment]
JFYI, I've switched to the Google Meet segmentation model as default (see also #28) and it works way better than either DeepLab or Body-Pix. Closing this for now.
