### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by googlinggreg** [floe/deepbacksub#27]
Hello,

Although I followed the directions on the OpenCV site to install, when I run make on the deepbacksub project it still gives me the error:
Makefile:23: *** Couldn't find OpenCV.  Stop.

Could anyone suggest the proper way to install OpenCV? Maybe I'm missing something.

**Comment by floe** [comment]
That means that `pkg-config` can't find OpenCV. What platform are you using? On Ubuntu and friends, the easiest way is to install the `libopencv-dev` package.

**Comment by googlinggreg** [comment]
Thanks, that worked! Way easier than the tutorials I was using. Is there anything else I need to do? I have tensorflow set up in the home directory, but when I run make now it says:

`g++ deepseg.cc loopback.cc -Ofast -march=native -fno-trapping-math -fassociative-math -funsafe-math-optimizations -Wall -pthread -I ../tensorflow.git -I ../tensorflow.git/tensorflow/lite/tools/make//downloads/absl -I ../tensorflow.git/tensorflow/lite/tools/make//downloads/flatbuffers/include -I/usr/include/opencv4/opencv -I/usr/include/opencv4 -lrt -ldl -L ../tensorflow.git/tensorflow/lite/tools/make//gen/linux_x86_64/lib/ -ltensorflow-lite -ldl -lopencv_stitching -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_highgui -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_quality -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core -o deepseg
deepseg.cc:17:10: fatal error: tensorflow/lite/interpreter.h: No such file or directory
   17 | #include "tensorflow/lite/interpreter.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:27: deepseg] Error 1
`

**Comment by floe** [comment]
In the Makefile in line 6 (https://github.com/floe/deepbacksub/blob/master/Makefile#L6), you'll have to set the tensorflow  directory. By default, it points to `../tensorflow.git`, but you can set it to wherever your tensorflow installation is.

**Comment by googlinggreg** [comment]
Thanks so much, Floe!

It does get farther in the execution now, but it still gets stuck. I have tensorflow in the adjacent directory to deepbacksub. Cloning it to other locations didn't seem to help much, either. I'm running Ubuntu 20.10.

`g++ deepseg.cc loopback.cc -Ofast -march=native -fno-trapping-math -fassociative-math -funsafe-math-optimizations -Wall -pthread -I ../tensorflow -I ../tensorflow/tensorflow/lite/tools/make//downloads/absl -I ../tensorflow/tensorflow/lite/tools/make//downloads/flatbuffers/include -I/usr/include/opencv4/opencv -I/usr/include/opencv4 -lrt -ldl -L ../tensorflow/tensorflow/lite/tools/make//gen/linux_x86_64/lib/ -ltensorflow-lite -ldl -lopencv_stitching -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_highgui -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_quality -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core -o deepseg
In file included from ../tensorflow/tensorflow/lite/core/api/op_resolver.h:20,
                 from ../tensorflow/tensorflow/lite/model.h:25,
                 from ../tensorflow/tensorflow/lite/kernels/register.h:19,
                 from deepseg.cc:18:
../tensorflow/tensorflow/lite/schema/schema_generated.h:21:10: fatal error: flatbuffers/flatbuffers.h: No such file or directory
   21 | #include "flatbuffers/flatbuffers.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:27: deepseg] Error 1
`

**Comment by floe** [comment]
Unfortunately, you can't install tensorflow-lite from a package, you'll have to build it. The instructions are on https://github.com/floe/deepbacksub#requirements or also in the Makefile on line 12-13.

**Comment by googlinggreg** [comment]
Thank you! That got tensorflow-lite working. :)

Now, when I finally run deepbacksub though it gives the error:
deepseg: loopback.cc:57: int loopback_init(const char*, int, int, int):
Assertion `ret_code != -1' failed.

**Comment by floe** [comment]
Hm... at this point, you could try to unload and re-load the v4l2-loopback module. You should also try to check which /dev/video* device corresponds to which physical/virtual device and adjust the commandline parameters if needed.

**Comment by googlinggreg** [comment]
Thank you! That worked, it was a different dev/video device.
