### ISSUE TITLE
hope support mobilenetv3 small

### ISSUE THREAD

**Issue by jiangjianping** [floe/deepbacksub#28]
hello Floe,

Could you tell me how to add the support of mobilenetv3 small?

**Comment by floe** [comment]
Not quite sure what you mean, deeplab v3 is already based on mobilenet v3? Or do you have a link for the specific network you want to support?

**Comment by jiangjianping** [comment]
FYI
https://ai.googleblog.com/2020/10/background-features-in-google-meet.html

**Comment by floe** [comment]
Ah, interesting. First thing you would need is the actual model file in `.tflite` format, apparently it's not available in https://github.com/google/mediapipe/tree/master/mediapipe/models ?

**Comment by jiangjianping** [comment]
Mobilnetv3 Large?
https://tfhub.dev/sayakpaul/lite-model/deeplabv3-mobilenetv3-cityscapes/1/default/2

**Comment by floe** [comment]
Deeplab v3 is exactly what my project here already uses: https://github.com/floe/deepbacksub/blob/master/deeplabv3_257_mv_gpu.tflite

The only difference I can see is that the one you just posted is trained on Cityscapes, which won't help a lot with person segmentation.

The one from Google Meet would be much more interesting, because it is specifically optimized for person segmentation, but you would need to find the specific `.tflite` file for that Google Meet network.

**Comment by jiangjianping** [comment]
Floe,
Thanks, Hope lucky to get that tfilte. Do you have idea about joint bilateral filter?

**Comment by floe** [comment]
Right now, it seems you can download the models from https://meet.google.com/_/rtcvidproc/release_1wttl/345264209/segm_full_v679.tflite and https://meet.google.com/_/rtcvidproc/release_1wttl/345264209/segm_lite_v681.tflite - and according to the [model card](https://drive.google.com/file/d/1WvHxUONoATFJ9JpSgAF7dU_F5V58HItS/view) they should be licensed with Apache 2.0, so you should in theory be allowed to re-use them. I'll give it a try and see if these can be integrated.

**Comment by jiangjianping** [comment]
Floe,
Great! Thanks a lot.

**Comment by jiangjianping** [comment]
Hello Floe,
I tried the new model, but the AllocateTensors() failed. I guess that the xnnpack need to be included.

**Comment by jiangjianping** [comment]
Got  something may be useful

https://github.com/tensorflow/tfjs/issues/4177

**Comment by floe** [comment]
I've just copied the relevant custom op from MediaPipe for now. See latest commit (https://github.com/floe/deepbacksub/commit/306da1b8869f75874a600cad3352ee11cc6071a3) for a implementation that's somewhat working (still some sort of synchronization error between capture thread and network evaluation happening here, though).

**Comment by jiangjianping** [comment]
Great! I will try.

**Comment by floe** [comment]
I'm closing this for now, thanks for pointing me to the Google Meet segmentation model. Please open a new issue if something is still wonky.

**Comment by fransiskusyoga** [comment]
Hello, I am trying to run google meet model on windows. But I still don't have any idea how to integrate the custom op from mediapipe. I cannot load the model using normal runtime because it doesn't have the custom operation.

**Comment by floe** [comment]
You need `transpose_conv_bias.*` from https://github.com/google/mediapipe/tree/master/mediapipe/util/tflite/operations and register them as in https://github.com/floe/deepbacksub/blob/master/deepseg.cc#L252-L258.

**Comment by fangfufu** [comment]
Mediapipe officially released selfie segmentation support. You might want to update your app. 
https://github.com/google/mediapipe/releases/tag/v0.8.5
