### ISSUE TITLE
Core dump while running deepseg

### ISSUE THREAD

**Issue by binithb** [floe/deepbacksub#31]
inithb@pop-os:~/workspace/github/deepbacksub$ ./deepseg -d -d -c /dev/video0 -v /dev/video1
deepseg v0.2.0
(c) 2021 by floe@butterbrot.org
https://github.com/floe/deepbacksub
debug:  2
ccam:   /dev/video0
vcam:   /dev/video1
width:  640
height: 480
back:   images/background.png
threads:2
model:  models/segm_full_v679.tflite

*deepseg: loopback.cc:58: int loopback_init(const char*, int, int, int): Assertion `ret_code != -1' failed.*
Aborted (core dumped)
binithb@pop-os:~/workspace/github/deepbacksub$ ls -ltr /dev/video*
crw-rw----+ 1 root video 81, 1 Jan 18 12:37 /dev/video1
crw-rw----+ 1 root video 81, 0 Jan 18 12:37 /dev/video0
crw-rw----+ 1 root video 81, 2 Jan 18 12:38 /dev/video2
crw-rw----+ 1 root video 81, 3 Jan 18 12:38 /dev/video3
crw-rw----+ 1 root video 81, 4 Jan 18 12:54 /dev/video4
binithb@pop-os:~/workspace/github/deepbacksub$ cat /etc/i
ifplugd/                 init.d/                  initramfs/               initramfs-tools/         inputrc                  insserv.conf.d/          io.elementary.appcenter/ iproute2/                issue                    issue.diverted           issue.net                issue.net.diverted       
binithb@pop-os:~/workspace/github/deepbacksub$ cat /etc/issue
Pop!_OS 20.04 LTS \n \l

[deepseg_core_popos20.zip](https://github.com/floe/deepbacksub/files/5830273/deepseg_core_popos20.zip)
binithb@pop-os:~/workspace/github/deepbacksub$ uname -a
Linux pop-os 5.8.0-7630-generic #32~1609193707~20.04~781bb80-Ubuntu SMP Tue Jan 5 21:23:50 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
binithb@pop-os:~/workspace/github/deepbacksub$

**Comment by binithb** [comment]
( I had done some other experiments with v4l2loopback before finding deepbacksub and I think that's why there are many files with prefix video in /dev). Not sure if that is related to the issue, just saying.

**Comment by floe** [comment]
When `loopback_init` fails, then I'm 99% sure that `/dev/video1` is not the correct virtual device. Running `v4l2-ctl --list-devices` should give you some more details.

Also, sometimes v4l2loopback can get stuck, so try unloading and reloading the kernel module.

**Comment by BenBE** [comment]
I'd appreciate that instead of an assertion deepseg would exit normally with a proper error message. Ideally even with some helpful information for the user.

**Comment by floe** [comment]
Agreed, that's a leftover from the loopback example code.

**Comment by floe** [comment]
Will be closed by #36 as well.
