### ISSUE TITLE
Person is only picked up on part of the video image

### ISSUE THREAD

**Issue by nickperkins** [floe/deepbacksub#32]
For some reason, I'm cut off on one side of the video. You can see the hard cut on the left side.

When using the google meet model, it's even worse and only detects on the right half of the video. Any ideas?

```
./deepseg -c /dev/video0 -v /dev/video4 -m models/deeplabv3_257_mv_gpu.tflite -b images/bac.jpg -t 16
deepseg v0.2.0
(c) 2021 by floe@butterbrot.org
https://github.com/floe/deepbacksub
debug:  0
ccam:   /dev/video0
vcam:   /dev/video4
width:  640
height: 480
back:   images/bac.jpg
threads:16
model:  models/deeplabv3_257_mv_gpu.tflite
```
![image](https://user-images.githubusercontent.com/569924/105255687-c5cf7f00-5bcf-11eb-9905-30ba07ee83fc.png)

**Comment by nickperkins** [comment]
Sorry, I solved this issue at my end.

**Comment by floe** [comment]
Just for completeness' sake, the models usually have either square or portrait-format aspect ratio for the input, so I have to take a square/portrait region out of the landscape camera image...
