### ISSUE TITLE
Improve temporal stability of masked image

### ISSUE THREAD

**Issue by BenBE** [floe/deepbacksub#34]
The masked image is often quite unstable in regards to the flow of time. While certain details may appear in one frame they might be gone in the next frame. This is in particular distracting if this affects part of the body or face (not necessarily the borders).

Maybe decrease the likelyhood of a pixel being removed from the mask on the amount of pixels that changed mask membership in their neighborhood: I.e. the more pixels in an area suddently change membership, the less likely it is that the whole area should be removed.

**Comment by floe** [comment]
I have two ideas for solving this (which are non-exclusive):

- use a weighted moving average over the last n frames
- use a outline/hull function to close "holes" inside the silhouette

Will probably try to implement this soon-ish (exam period ATM). Pull requests welcome, of course :-)

**Comment by BenBE** [comment]
The days when I had image processing in university are unfortunately quite a few years back …

For the weighted average: Combine with gamma correction of likelyhood detection by the NN. With the hard segmentation (softmax) only after the averaging …

Both seem reasonable although my gut feeling suggests the first option may be more promising when trying to avoid the flicker of the misdetections.

P.S.: Good luck with your exams.

**Comment by phlash** [comment]
Seems related to #29 with the segm models?

**Comment by BenBE** [comment]
Similar, but not quite. This issue is for WHEN the model segments a proper image that it sometimes (for only a few frames) removes large portions of the segmentation.

#29 is primarily about the model not segmenting correctly in the first place.

With #29 resolved you'd get a proper image, which still might flicker from time to time.
With this image result, you might not get the proper image, but the part it shows is consistent over time.

**Comment by floe** [comment]
WMA was pretty straightforward to implement and does look noticeably better, IMHO.
