### ISSUE TITLE
MAC Support

### ISSUE THREAD

**Issue by csverma610** [floe/deepbacksub#37]
Hello,

Thank you very much for your code on Github. I was wondering if there is a way to port this code on Mac. Any suggestion
will be helpful.

**Comment by BenBE** [comment]
This is quite unlikely as this tool uses a Linux Kernel module to allow for a loopback camera device to be created. Unless there is some similar functionality available on Mac it's not possible to easily reuse or port this tool to Mac.

**Comment by floe** [comment]
There is a similar tool for Mac called CamTwist. Open Broadcast Studio (OBS) might also work. See #10 for details.
