### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by testing6ui** [floe/deepbacksub#44]
Hello,
I got the following error:
```
deepseg v0.2.0
(c) 2021 by floe@butterbrot.org
https://github.com/floe/deepbacksub
debug:  2
ccam:   /dev/video0
vcam:   /dev/video1
width:  640
height: 480
flip_h: no
flip_v: no
threads:2
back:   (none)
model:  models/segm_full_v679.tflite

deepseg: loopback.cc:58: int loopback_init(const char*, int, int, int): Assertion `ret_code != -1' failed.
Aborted (core dumped)
```

**Comment by testing6ui** [comment]
same as #31

**Comment by BenBE** [comment]
This is caused when deepbacksub can't open target camera device from the `v4l2loopback` kernel module for sending the output stream to. Unfortunately the error message is not very descriptive.

Please check you have a recent version of the `v4l2loopback` kernel module loaded. For Debian and Ubuntu there's a DKMS package you can install directly which works fine. Also check that `/dev/video1` is indeed the device created by `v4l2loopback`.
