### ISSUE TITLE
Custom Training

### ISSUE THREAD

**Issue by KaratekHD** [floe/deepbacksub#56]
I just discovered this software and it works, but not particularly well. If I want it to detect me, I have to be farer away from my PC than my headphone cable reaches, so it would be pretty nice if I could train it for myself. Is something like this implemented and if yes how does it work?

**Comment by phlash** [comment]
Currently this is just an inference engine to host the pre-built Tensorflow lite models from Google and other researchers, it has no ability to train new models, that's a much harder problem!

Have you tried the various detection models available? We often see better results with the `deeplabv3_257_mv_gpu.tflite` model than the default segm one...
