### ISSUE TITLE
Other segmentation models

### ISSUE THREAD

**Issue by MartinKlevs** [floe/deepbacksub#62]
I have stumbled upon this repo:
[Portrait-segmentation](https://github.com/anilsathyan7/Portrait-Segmentation)

It contains multiple portrait segmentation models, mostly geared towards smartphones. Some of the models seem pretty good and fast. Would it be possible to implement some of these models here?

**Comment by BenBE** [comment]
To implement those models we mostly need to have them in tflite format and need to know which aspect ratio and input dimensions they need. Also some models may need additional operations for pre- and post-processing. So basically yes, but …

**Comment by MartinKlevs** [comment]
The `/models` folder seems to contain some `*.tflite` files. Are those in the same format that is used here? The repo contains python scripts to demo the models with opencv, so i think that the pre/post processing steps can be reverse-engineered.

**Comment by phlash** [comment]
Wow, that's pretty comprehensive research, someone's PhD I think!  As @BenBE says - it should be possible to test the tflite models, provided we understand the I/O formats (as you note, derivable from the code, if not documented already). Finding the time... more challenging, but someone may feel inspired to have a go :)

We have sufficient timing through the code to know if these models are fast enough, and subjective testers abound to determine the quality of segmentation!

**Comment by floe** [comment]
Let's continue this discussion in #58 and close here, just to keep the issues list manageable.
