### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by SANDRORRFREIRE** [floe/deepbacksub#69]
Hi, congratulation, escuse my bad english

My problem is, I use lenovo (notepad) cam EasyCamera embeeded

deepseg v0.2.0
(c) 2021 by floe@butterbrot.org
https://github.com/floe/deepbacksub
debug:  2
ccam:   /dev/video0
vcam:   /dev/video1
width:  640
height: 480
flip_h: no
flip_v: no
threads:2
back:   (none)
model:  models/segm_full_v679.tflite

loopback.cc:66(loopback_init): Failed to set device video format: Invalid argument
Failed to initialize vcam device.

**Comment by ydbondt** [comment]
Don't forget the modprobe command and check which video device is created in /dev/video*.

**Comment by phlash** [comment]
You can specify numbering and device names, here's what I have:
to ensure the loopback module is loaded:
```
/etc/modules-load.d/v4l2loopback.conf:
v4l2loopback
```
to configure the loopback module with two additional devices, /dev/video10 == 'Virtual Camera' /dev/video11 == 'Test Loopback':
```
/etc/modprobe.d/v4l2loopback-options.conf:
options v4l2loopback video_nr=10,11 exclusive_caps=1 card_label="Virtual Camera,Test Loopback"
```

**Comment by SANDRORRFREIRE** [comment]
Tks
Is working now, but in green screen.
What replace the background image.

Regards

**Comment by BenBE** [comment]
You need to provide an image file with `-b`. See also the usage information shown with `-?` for further details.

**Comment by phlash** [comment]
@SANDRORRFREIRE is this fixed for you now?

**Comment by phlash** [comment]
No feedback, closing.

**Comment by cojack** [comment]
@SANDRORRFREIRE how did you fix that issue?

**Comment by phlash** [comment]
@cojack at a guess, I think @SANDRORRFREIRE sorted out their v4l2loopback devices (see my earlier description of how I have mine arranged), then discovered the -b option to load a background image :smile:
