### ISSUE TITLE
Make to-do list

### ISSUE THREAD

**Issue by MartinKlevs** [floe/deepbacksub#71]
Would it be useful to make a list that tracks features that could be added in the future?

**Comment by BenBE** [comment]
We could just add a label for such a wishlist.

**Comment by floe** [comment]
Isn't this exactly what the "enhancement" label is designed for?

**Comment by MartinKlevs** [comment]
Agreed.

**Comment by BenBE** [comment]
@floe I see a minor difference between Wishlist (Things that are really nice to have, but without commitment to implement) and Enhancement (This would make things definitively better and we really should get going to implement them). But ya, Enhancement also kinda WFM …
