### ISSUE TITLE
Aspect ration seems broken if changed.

### ISSUE THREAD

**Issue by MKrabs** [floe/deepbacksub#73]
Everything is working fine, but the aspect ratio seems to be 9:16 (vertical video) which is odd.

Doing a basic `$ ./deepseg -d -d -c /dev/video0 -v /dev/video2` works but leaves me with a vertical aspect ratio.. [> image](https://imgur.com/a/WNqtBgB)

Changing the video in any shape or form `$ ./deepseg -d -c /dev/video0 -v /dev/video2 -w 720 -h 480` gives an unusable video output, turns the person into a black/dark blob and OBS loops the last 2 frames rapidly (wierd artifacts). [> image](https://imgur.com/B6jYtOM)

Debug:
```
$ ./deepseg -c /dev/video0 -v /dev/video2
deepseg v0.2.0
(c) 2021 by floe@butterbrot.org
https://github.com/floe/deepbacksub
debug:  0
ccam:   /dev/video0
vcam:   /dev/video2
width:  640
height: 480
flip_h: no
flip_v: no
threads:2
back:   (none)
model:  models/segm_full_v679.tflite

Startup: 28871574ns
```

Thanks for the hard work you put into this

**Comment by floe** [comment]
The `segm_full_v679.tflite` model is designed for portrait input, so we can either scale down the input image or make a portrait cutout. But the newer "selfie" model (`models/selfiesegmentation...tflite`) is more accurate and has a square input shape, I suggest to try that one instead.
