### ISSUE TITLE
Gpu vs Edge TPU

### ISSUE THREAD

**Issue by I-B-CC** [floe/deepbacksub#8]
Have you given any thought to offloading the processing to a TF core?  Something like a Coral USB TPU.

**Comment by floe** [comment]
Don't have access to any TPU device, but AFAIK all TFLite models should be TPU-compatible?

**Comment by I-B-CC** [comment]
No worries, thanks for the response! To the best of my understanding (still learning) it's close but not identical, any tf model has to be converted to run efficiently for tflite, but it's definitely closer than if you tried to covert from a Caffe model.

**Comment by floe** [comment]
In the meantime, I've managed to retrain the original DeepLab v3+ network specifically for person segmentation, hopefully with somewhat improved performance. However, converting that TF network to TFLite is not at all straightforward, as I've found. Any pointers would be great :-)

**Comment by I-B-CC** [comment]
No pointers as I have yet to successfully convert a model myself. But the week is only half over...
