### ISSUE TITLE
Assertion in loopback_init

### ISSUE THREAD

**Issue by henols** [floe/deepbacksub#9]
Hi
When im trying to run deepseg I get an assertion when trying to set **VIDIOC_S_FMT**
``deepseg: loopback.cc:57: int loopback_init(const char*, int, int, int): Assertion `ret_code != -1' failed.
``
I put an assertion after VIDIOC_G_FMT and the return code is also -1.

My loopback is configured to /dev/video2 and I have changed to that in deepseg.cc.

Any idea how to proceed from here?

**Comment by floe** [comment]
Hm, sometimes v4l2-loopback can get stuck in a specific configuration and refuses to change. Have you tried removing and reloading the kernel module?

**Comment by phlash** [comment]
I find that v4l2-loopback won't permit format changes while another app is reading from it.
`fuser -v /dev/video*` is really helpful in identifying the culprit.

**Comment by henols** [comment]
I think it was locked by something, like @phlash sad. I tried to uninstall the loopback module but that didnt help, I ended up rebooting the computer and then it worked.
